version: "3"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: super_secret
      POSTGRES_USER: app
      POSTGRES_DB: neighbourify
      POSTGRES_HOST: postgres
    ports:
      - "5432:5432"
    networks:
      - backend
  app:
    build: .
    command: bash -c "./wait-for-it.sh -t 0 postgres:5432 -- python manage.py makemigrations  && python manage.py migrate && python manage.py runserver 0.0.0.0:8990"
    environment:
      POSTGRES_PASSWORD: super_secret
    volumes:
      - .:/app
    ports:
      - "8990:8990"
    depends_on:
      - postgres
    networks:
      - backend
    entrypoint: ./entrypoint.sh
    restart: always
networks:
  backend:
